### PR TITLE
Accept `T2` by `B1` mention check

### PR DESCRIPTION
**Pull request by ggwpez**
Changes to a runtime API need a `B1` label, but `B1` rejects `T2`.  Therefore:
- Accept the `T2` label when `B1` is specified

MR https://github.com/paritytech/polkadot/pull/6536 and https://github.com/paritytech/cumulus/pull/2073 suffer from this.  
TODO:  
- [ ] Add tests

### CODE REVIEW

**Comment by ggwpez** [comment]
After talking to @chevdor I settled to use a mix of the existing pallets.

**Review by the-right-joyce — APPROVED** [review]

**Comment by chevdor** [comment]
After some checking with Oliver, I think we can summarize this way:

The issue is that `T0` and `T1` are orthogonal: We can (according to our rules) have only one of them and we must have at least one of them.

Adding `T2` is not an issue. But removing `T1` while not having a `T0` instead is not legal with the current rules.

@the-right-joyce it may be easier to move T0 and T1 away from the `Ts` and keep them with a letter that is exclusive.
That would also free 2 spots in the non exclusive `Ts`.

For now, it sounds like @ggwpez can live with adding back `T1` on the mentioned PRs.

**Comment by chevdor** [comment]
There are 2 rules at play here and I missed that in my inital review:
https://github.com/paritytech/labels/blob/main/ruled_labels/specs_cumulus.yaml#L219-L231

Those say:
- if we have B1, we must have 1 and only 1 of the set [T0, T1]
- if we have B1, we must have 1..n of the set [T*]

We need to make both those rules happy.

**Comment by ggwpez** [comment]
Going to merge this now since I think its a valid use-case. However, in the MR that i mentioned it probably makes more sens to use both labels, since it does slightly alter the runtime blob.

**Pull request merged**
